version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-app
    depends_on:
      - db
    environment:
      - DATABASE_NAME=pars_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

  db:
    image: postgres:13
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: pars_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
